[rest]
host = "127.0.0.1"
port = 8081

[grpc]
host = "127.0.0.1"
port = 50051

[stego_wave_lib]
header = "STEG"
default_lsb_deep = 1
max_occupancy = 70

[sw]
hide_file_prefix = "sw_"
clear_file_prefix = "c"